name: Angular Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.13"

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npx nx lint your-app-name

      # Uncomment and replace `your-app-name` with your actual app name for unit tests
      # - name: Unit tests
      #   run: npx nx test your-app-name

      - name: Build Angular App for Production
        # Replace `your-app-name` with your actual app name. Add any additional build options you need.
        run: npx nx build --configuration=production

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v12.9.0
        with:
          args: deploy --only hosting --project travel-on-811d5
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
