name: Angular CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.19' # Change this to your preferred Node.js version

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: ng lint

      - name: Unit tests
        run: ng test

      - name: Build
        run: ng build --prod # For production build. Use 'ng build' for development build.

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: dist/your-app-name # Replace 'your-app-name' with the actual name of your Angular app
