
name: Deploy to Firebase Hosting on Main Push
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.19'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project dvir-monajem-portfolio
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
